"""initial_schema

Revision ID: af970266ed45
Revises:
Create Date: 2025-12-27 19:39:58.570853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af970266ed45"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "last_synced_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.create_index(
            "idx_contacts_duplicate_group", ["duplicate_group_id"], unique=False
        )
        batch_op.create_index("idx_contacts_linkedin", ["linkedin"], unique=False)
        batch_op.create_index("idx_contacts_website", ["website"], unique=False)

    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "contact_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "contacts", ["contact_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("note_contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "note_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "contact_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "contacts", ["contact_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "notes", ["note_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "event_time",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "last_synced_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    with op.batch_alter_table("phones", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "contact_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "contacts", ["contact_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("reminder_contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "reminder_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "contact_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "reminders", ["reminder_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "contacts", ["contact_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "last_synced_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the database schema changes applied by the migration's upgrade.
    
    Restores original column types and nullability for reminders, reminder_contacts, phones, notes, note_contacts, emails, and contacts; recreates original foreign key constraints without ON DELETE CASCADE and restores autoincrementing integer primary keys where applicable; and removes the indices added on contacts (`idx_contacts_duplicate_group`, `idx_contacts_linkedin`, `idx_contacts_website`).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.alter_column(
            "last_synced_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("reminder_contacts", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "reminders", ["reminder_id"], ["id"])
        batch_op.create_foreign_key(None, "contacts", ["contact_id"], ["id"])
        batch_op.alter_column(
            "contact_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )
        batch_op.alter_column(
            "reminder_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("phones", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "contacts", ["contact_id"], ["id"])
        batch_op.alter_column(
            "contact_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.alter_column(
            "last_synced_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "event_time",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("note_contacts", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "notes", ["note_id"], ["id"])
        batch_op.create_foreign_key(None, "contacts", ["contact_id"], ["id"])
        batch_op.alter_column(
            "contact_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )
        batch_op.alter_column(
            "note_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "contacts", ["contact_id"], ["id"])
        batch_op.alter_column(
            "contact_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index("idx_contacts_website")
        batch_op.drop_index("idx_contacts_linkedin")
        batch_op.drop_index("idx_contacts_duplicate_group")
        batch_op.alter_column(
            "last_synced_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    # ### end Alembic commands ###